### ISSUE TITLE
Wrong ffmpeg.path if asar is enabled

### ISSUE THREAD

**Issue by espresso3389** [kribblo/node-ffmpeg-installer#10]
ffmpeg.path returns path like `....\resources\app.asar\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe` regardless of asar state.
It should return `....\resources\app.asar.unpacked\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe` if asar is enabled.

**Comment by kribblo** [comment]
Looks like this known issue: https://github.com/electron-userland/electron-packager/issues/740

It should be the responsibility of asar not to break paths, IMO.

**Comment by kribblo** [comment]
Added a note with workaround to the README: https://github.com/kribblo/node-ffmpeg-installer/blob/master/README.md#wrong-path-under-electron-with-asar-enabled

Handling special cases like that is outside the scope of ffmpeg-installer

**Comment by espresso3389** [comment]
I see. Thanks so much for your information.
