### ISSUE TITLE
Video output contains green artifacts

### ISSUE THREAD

**Issue by joshbg2k** [kribblo/node-ffmpeg-installer#12]
Hoping someone might know how to resolve this. I'm calling ffmpeg using `child_process.exec` in Electron to create a slideshow video from a set of images. Usually this results in green artifacts spanning the width of the video and going anywhere between the lower and upper quarters of the video height. Other than the image artifacts the video outputs with expected settings (frame rate, etc).

When I run the same command on the same image content on the same copy of ffmpeg in a terminal window outside my app, everything works fine. It looks like this:

`/path/to/ffmpeg -f image2 -framerate 8 -i "/path/to/images/img%02d.jpg" -c:v libx264 "/path/to/video.mp4"`

Playing around with the ffmpeg options has not worked. I'm inclined to think it has something to do with how `child_process` executes it. Any ideas?

**Comment by kribblo** [comment]
I have little to no idea of the inner workings of either node, electron or ffmpeg and I don't think too many people will see this issue, you might be better off asking on Stackoverflow and/or the forums for node, electron and ffmpeg if someone recognizes this.

One thing though, if you do this outside of electron, with just a small node program, does it do the same? Could help narrow it down if it only happens inside electron.

**Comment by joshbg2k** [comment]
Thanks, that's a good thought, I'll try this outside of Electron and see what happens.
