### ISSUE TITLE
Rubberband missing

### ISSUE THREAD

**Issue by binarykitchen** [kribblo/node-ffmpeg-installer#14]
It's me again. Turns out the important rubberband filter is missing in the ffmpeg binaries of this package:

```
No such filter: 'rubberband'
```

Would it be too much to ask for adding that filter too?

**Comment by binarykitchen** [comment]
Right, will ask them now

**Comment by binarykitchen** [comment]
Done. Worked with the guy from https://evermeet.cx/ffmpeg/ and his latest version has rubberband and works well. Can you update reference to it?

**Comment by kribblo** [comment]
Yeah sure np. Guess you only use the Mac version then? I guess if others need this for other platforms they will have to do the same work you did. :)

**Comment by binarykitchen** [comment]
The others are fine and already have librubberband in them.

**Comment by kribblo** [comment]
Alright, can you try the latest now? Sorry forgot about writing a comment, just uploaded a new version.

**Comment by binarykitchen** [comment]
will check out once latest version is on npm

**Comment by binarykitchen** [comment]
any estimates when you will publish @kribblo ?

**Comment by kribblo** [comment]
Well it should have been published when I said I did a week ago or so?

**Comment by kribblo** [comment]
Did it fail?

**Comment by binarykitchen** [comment]
Ah yeah, works now - rubberband is in :)

**Comment by kribblo** [comment]
Great!
