### ISSUE TITLE
unable to find libasound_module_conf_pulse.so, 64bit linux

### ISSUE THREAD

**Issue by durga598** [kribblo/node-ffmpeg-installer#16]
I am getting this error when I try to caputre audio through alsa device in my 64bit ubuntu system.
>ALSA lib ../../src/conf.c:3545:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib/alsa-lib/libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM hw:0

`libasound_module_conf_pulse.so` is present in `usr/lib/x86_64-linux-gnu/alsa-lib`

**Comment by kribblo** [comment]
Hello! This project only installs ffmpeg built by others, so probably it's a better idea to ask the person who built this for Linux 64-bit: https://www.johnvansickle.com/ffmpeg/

**Comment by kribblo** [comment]
It could definitely be that a later version fixes this bug, in which case I'll be happy to update.

**Comment by kribblo** [comment]
Did an update today to latest Linux builds, see if that helps, otherwise the previous advice still applies to see if the maintainer of the binaries can help fix it.

**Comment by durga598** [comment]
Getting the same issue. `ubuntu version 16.04`

**Comment by kribblo** [comment]
Guess you could try (re)installing libasound2-plugins

    sudo apt install libasound2-plugins

But otherwise I'd google the problem, looks like you have some missing package that ffmpeg expects.
