### ISSUE TITLE
Unable to install linux-x64 binary

### ISSUE THREAD

**Issue by Travo100** [kribblo/node-ffmpeg-installer#21]
Hello there! I've been using this package for a Linux server running node on AWS. The installer was working until around December 10th, 2018, and now my server is crashing and I'm getting an error in my logs.

Working locally on OSX and Windows things have been working perfectly, but Linux seems to be having the issue. 

Any insight would be greatly appreciated!

Error below:
```
/var/app/current/node_modules/@ffmpeg-installer/ffmpeg/index.js:37
    throw 'Could not find ffmpeg executable, tried "' + npm3Binary + '" and "' + npm2Binary + '"';
    ^
Could not find ffmpeg executable, tried "/var/app/current/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/var/app/current/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
```

**Comment by kribblo** [comment]
Hmm I upgraded the binary just the other day but made no other changes to code or paths. What happens if you go back to 1.0.16? Is the install paths cleaned out between builds? There should have been no other change and I don't see anything sticking out in the logs, but let's see if we can fix this.

**Comment by kribblo** [comment]
Also, is the binary installed somewhere you can find, but not in the expected path?

**Comment by Travo100** [comment]
Hey @kribblo so I downgraded back to 1.0.16 and still the same error. I'm in the process of creating a whole new environment for the server and going to try again totally fresh. I'll keep you posted with the results. Thank you for your quick response BTW.

**Comment by kribblo** [comment]
Thanks, let me know what you find. It still works in our builds at work, so not really sure what is happening here, but please check if you can find out if the binary is not installed at all, or in an unexpected place, if possible!

**Comment by Travo100** [comment]
Hey @kribblo I was able to ssh into my test server where the only thing it installs is express and @ffmpeg-installer. Looked the node_modules where you'd expect the binary to be and it is not there. I built this environment from total scratch so something is going on with AWS here. I was able to get the same app going in no time using Heroku. Either way here are the result of my find on my server:

```
[ec2-user node_modules]$ find \@ffmpeg-installer/
@ffmpeg-installer/
@ffmpeg-installer/ffmpeg
@ffmpeg-installer/ffmpeg/package.json
@ffmpeg-installer/ffmpeg/lib
@ffmpeg-installer/ffmpeg/lib/verify-file.js
@ffmpeg-installer/ffmpeg/README.md
@ffmpeg-installer/ffmpeg/index.js
```

**Comment by Travo100** [comment]
So it was a permissions thing with AWS. I had to add a `.npmrc` file with the following to get it to kick off the making of the binary.

`unsafe-perm=true`

After that things worked perfectly. I'm going to close this issue now because it's nothing to do with the code of this package. Thank you for your help @kribblo!

**Comment by kribblo** [comment]
Hey, sorry for the late reply, been mostly offline during holidays, but great that it all worked out! Do you think this is something that might be useful to have in the README, say under known issues?

**Comment by Travo100** [comment]
I would say so. Just spinning up a default Elastic Beanstalk instance through their GUI it would fail at the start due to the binary not being allowed to download.

**Comment by davidavz** [comment]
Hi there 👋

I have exactly the same problem installing it via GitHub Action, but I'm using npm version 7.7.6 and `unsafe-perm` does not exist anymore.
Should I run `sudo npm i` instead ? (I tried but still the same problem)

**Comment by davidavz** [comment]
Actually I just needed to run `npm install @ffmpeg-installer/linux-x64 --force` and it works now 👍
