### ISSUE TITLE
Request for ARM support

### ISSUE THREAD

**Issue by bartbutenaers** [kribblo/node-ffmpeg-installer#22]
Hi Kristoffer (@kribblo),

When I try following code on a Raspberry Pi 3 Model B (running Raspbian):
```
    const ffmpeg = require('@ffmpeg-installer/ffmpeg');
    console.log(ffmpeg.path, ffmpeg.version);
```
Then the result is "_Unsupported platform/architecture: linux-arm_".

Do you have plans to support ARM processors?  
Perhaps following information allows you to determine whether it is possible or not:
+ Seems that [Debian](https://www.debian.org/ports/arm/) supports 3 ports of ARM hardware (**armhf** / **armel** / **arm64**), where both armhf and armel are 32-bit.
+ I found two ways to determine the hardware: see [1](https://blogs.oracle.com/jtc/is-it-armhf-or-armel) and [2](https://unix.stackexchange.com/questions/180726/easy-command-line-method-to-determine-specific-arm-architecture-string/181538).
+ And [here](https://ffbinaries.com/downloads) there are binaries available for armhf/armel/arm64.

Thanks for your time !!
Bart

**Comment by kribblo** [comment]
No plans as such, but not opposed to it either! You have already done some of the research I see. If you like to do a pull request it would be even faster, otherwise I will look into it

**Comment by bartbutenaers** [comment]
Wow, that was fast ;-)
Glad to hear that you are not against it ...
Just saw on the [link ](https://www.johnvansickle.com/ffmpeg/) where you fetch your binaries, that armhf/rmel/arm64 binaries are also available.  So we can already forget about my link, to keep your code more consistent!
If you would have some time left to implement it, that would be highly appreciated!  Otherwise I will try to create a pull request.  But that might take a bit longer, since I'm not experienced with debugging such installer code ...

**Comment by Luisangonzalez** [comment]
Hello, I created pull request ;)
https://github.com/kribblo/node-ffmpeg-installer/pull/29

**Comment by kribblo** [comment]
Hello, I've merged and published, it took a while because npmjs decided to be a #¤%& about the email I already verified. I haven't tested it yet, but should be at version 1.0.18. See if it works for you. :)

**Comment by Luisangonzalez** [comment]
Hello,

Thanks;)

Yes, works perfect.

Tested in Raspberry Pi 3 Model B Plus Rev 1.3 on Raspbian Stretch .

**Comment by kribblo** [comment]
Great, closing this then. Thanks!

**Comment by kribblo** [comment]
Ah, one more thing: could you provide the sources as with the others for the README?

**Comment by Luisangonzalez** [comment]
Yes, the same, https://johnvansickle.com/ffmpeg/

arm: https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-armhf-static.tar.xz
arm64: https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-arm64-static.tar.xz
