### ISSUE TITLE
node ffmpeg installer not working on Lambda

### ISSUE THREAD

**Issue by jaman99** [kribblo/node-ffmpeg-installer#28]
Node ffmpeg installer not working on Lambda please help me :-)

**Comment by SavageCore** [comment]
See this: https://github.com/kribblo/node-ffmpeg-installer#aws-andor-elastic-beanstalk

**Comment by kribblo** [comment]
@jaman99  did this help?

**Comment by PJCHENder** [comment]
I need to add 

```
npm install @ffmpeg-installer/linux-x64 --force
```

and it seems to be work. Find the solution at [Generate a video preview with FFMPEG on a node serverless Lambda (AWS)](https://medium.com/@identiqdev/generate-a-video-preview-with-ffmpeg-on-a-node-serverless-lambda-aws-1d0de834965c)
