### ISSUE TITLE
Wrong path for linux-ia32

### ISSUE THREAD

**Issue by seabrus** [kribblo/node-ffmpeg-installer#3]
Hi @kribblo,

First of all, thanks a lot for your great package. It is a really useful idea.

Today I've tried the package and encountered one problem: the path is incorrect. 
My situation:
- Linux 32 bit (LinuxMint 17.3 / Ubuntu 14.04)
- latest version of npm
- node 4.5.0

After executing the command `npm install --save @ffmpeg-installer/ffmpeg` I had the following file structure:
```
[ my_project_root ]
    /node_modules
        /@ffmpeg-installer
            /ffmpeg
                /node_modules
                    /@ffmpeg-installer
                        /linux-ia32
                            /ffmpeg
```
But the package gave me another result for the path:
'``[ my_project_root ]/node_modules/@ffmpeg-installer/linux-ia32/ffmpeg'``

The package returned  a correct version - "3.1.3".

I checked the test and the index.js files, and yep, their code produced '``[ my_project_root ]/node_modules/@ffmpeg-installer/linux-ia32/ffmpeg'``, not '``[ my_project_root ]/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-ia32/ffmpeg```. I repeated the installation in another directory - the same result.

Could you help with this? What is wrong in my actions?

Have a nice day.

**Comment by kribblo** [comment]
Hello, this looks like you have NPM version 2.X (I think that's correct for Node 4.X series) which used a deep folder structure, while NPM version 3.X uses a shallow folder structure.

Currently this only supports NPM v3, simply because I didn't think about NPM v2.

I will fix this soonish by checking which of the paths actually exists.

**Comment by seabrus** [comment]
Yes, you are right, my NPM is 2.15.9!

`I will fix this soonish by checking which of the paths actually exists` -- it wll be absolutely great, I'm looking forward to this update.

**Comment by kribblo** [comment]
@seabrus There is a new version now that *should* work, however I couldn't really verify since I don't have NPM v2. Can you test again?

**Comment by seabrus** [comment]
OK, take me 20 minutes

**Comment by seabrus** [comment]
It is OK now! Thanks a lot

I've tested it in pure node. A bit later I'll test also in a meteor app (in fact, I use your package and `fluent-ffmpeg` as part of a meteor project).

**Comment by kribblo** [comment]
@seabrus thanks!

I'm planning on using this in some in-house tools at work but it hasn't been in much actual use yet,  so I appreciate the feedback and testing.

**Comment by seabrus** [comment]
I've tried it in my app. It's cool. 

I found your package when decided to provide on server transformation for audio files. I'm planning to deploy my app on heroku first. The deployment procedure is not simple there. So I hope very much that your package will be really helpful there.

Yave a great night :)
