### ISSUE TITLE
how to install ia32 package on x64 device?

### ISSUE THREAD

**Issue by Ivorfason** [kribblo/node-ffmpeg-installer#31]
the issue on Windows

**Comment by kribblo** [comment]
Hello, I'm not sure if you can. The package is using the internal npm properties of cpu, os etc and they are determined by the node.js version you are using. It might be possible that it could work if you install using a ia32 node.js version, but otherwise this is all controlled by the npm system.

**Comment by kribblo** [comment]
It's all meant to "just work" on multiple systems, not to do cross-platform stuff on the same machine.

**Comment by Ivorfason** [comment]
> It's all meant to "just work" on multiple systems, not to do cross-platform stuff on the same machine.

It works !!! Thank you very much
