### ISSUE TITLE
Does not work as sub dependency

### ISSUE THREAD

**Issue by sebakerckhof** [kribblo/node-ffmpeg-installer#32]
If I have the following dependencies:
`project A -> project B -> ffmpeg-installer`,

Then it I get the following error:
`Uncaught Could not find ffmpeg executable, tried "/home/seba/dev/project-a/node_modules/project-b/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/home/seba/dev/project-a/node_modules/project-b/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"`

Because the `node_modules` folder looks like ( with npm 6.4.1):
```
project A
|-node_modules
   |-@ffmpeg-installer
      |-node_modules
         |-linux-x64
            |-ffmpeg (=> binary it needs, but doesn't search this location)
   |-project-b
      |-node_modules
         |-@ffmpeg-installer
            |-ffmpeg
```

**Comment by kribblo** [comment]
Pushed 1.0.19, please let me know if this works for you
