### ISSUE TITLE
Way to suppress  NPM warn logs on postinstall

### ISSUE THREAD

**Issue by mayeaux** [kribblo/node-ffmpeg-installer#35]
While installing the module I get these logs, such as : 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules/@ffmpeg-installer/linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
```

It's kind of ugly to spit out on an install, is there anyway I can suppress these warn logs specifically for this module?

**Comment by kribblo** [comment]
No, sorry, that's how the module avoids installing all binaries for all platforms: https://github.com/kribblo/node-ffmpeg-installer#warnings-during-install

**Comment by mayeaux** [comment]
No problem, thanks it's a very useful module
