### ISSUE TITLE
@ffmpeg-installer/linux-arm64 requires platform arm, not arm64

### ISSUE THREAD

**Issue by aquark** [kribblo/node-ffmpeg-installer#37]
When I `npm install @ffmpeg-installer/ffmpeg`  on an `arm64` platform, none of the binaries are installed. The problem is that it requires os `arm` instead of `arm64`.  Pull request incoming.

**Comment by kribblo** [comment]
Published, but have no access to an arm64 platform so please test.

**Comment by aquark** [comment]
Yep, tested using my fork and it works for me
