### ISSUE TITLE
Upload git builds or stay on stable

### ISSUE THREAD

**Issue by SavageCore** [kribblo/node-ffmpeg-installer#4]
Hey

What are your thoughts on including git builds? I would like access to nvenc in my project which is compiled in as of [ffmpeg-20160525-git-9591ca7-win64-static](https://ffmpeg.zeranoe.com/builds/readme/win64/static/ffmpeg-20160525-git-9591ca7-win64-static-readme.txt)

**Comment by kribblo** [comment]
I don't really have a strong personal opinion; as I've understood it, ffmpeg snapshots are usually pretty stable anyway so could just as well go that way.

Pull requests welcome, or just some good links to what you want.

**Comment by kribblo** [comment]
I guess the only thing I want is to be able to give some degree of guarantee that these are the real thing and likely to work. :)

**Comment by SavageCore** [comment]
Same thoughts as me then FFmpeg states

>FFmpeg has always been a very experimental and developer-driven project. It is a key component in many multimedia projects and has new features added constantly. Development branch snapshots work really well 99% of the time so people are not afraid to use them.

But still not entirely sure!

Perhaps a fork to install the bleeding edge? I am reluctant to just `npm run upload` with latest git builds...

**Comment by kribblo** [comment]
Since it looks like the recommended builds are the quite recent anyway, I've updated Windows versions to "20160924-1212e34", will do something similar for the other platforms later. 

It should have `--nvenc`enabled: https://ffmpeg.zeranoe.com/builds/readme/win64/static/ffmpeg-20160924-1212e34-win64-static-readme.txt

**Comment by kribblo** [comment]
All versions should now be updated to git version 1212e34 as of 1.0.5.
