### ISSUE TITLE
Typo in README.md?

### ISSUE THREAD

**Issue by seabrus** [kribblo/node-ffmpeg-installer#5]
Hi,

It looks like that in README.md instead of
### process.spawn()
```javascript
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
const spawn = require('child_process').spawn;
const ffmpeg = spawn('ffmpeg', args);
ffmpeg.on('exit', onExit);
```
something like
### process.spawn()
```javascript
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
const spawn = require('child_process').spawn;
const ffmpeg = spawn(ffmpegPath, args);     // < < < < < FIRST argument is changed
ffmpeg.on('exit', onExit);
```
should be written.

**Comment by kribblo** [comment]
Heh, yeah, good catch. Will fix. :)

**Comment by kribblo** [comment]
Sidenote: for a small change like this, if you edit the README directly in the GitHub interface, GitHub can make a pull request of the change for you, very useful!

**Comment by seabrus** [comment]
@kribblo OK, will use it!
