### ISSUE TITLE
MIDI support

### ISSUE THREAD

**Issue by mbilokonsky** [kribblo/node-ffmpeg-installer#6]
Hi, I'm hoping you can help me understand a problem we're having! When using this installer on a Mac, invoking `[this ffmpeg] -i song.midi output.mp4` works just fine. However, when running the same node code on Ubuntu fails because the linux build of ffmpeg provided can't seem to handle MIDI decoding.

Is this a known issue? How is the Darwin build different from the Linux build? Is there an easy way to add MIDI support to the linux build?

**Comment by kribblo** [comment]
I'm sorry, I'm in no way involved in the development of ffmpeg, however if you ask this question to the project (<https://ffmpeg.org/contact.html>) and find out that there's a version with MIDI support that I could upgrade this project to, I would be very happy to do so!

**Comment by kribblo** [comment]
Since I take the Linux builds from here: https://www.johnvansickle.com/ffmpeg/ you might even want to contact that person and ask if it's possible to enable midi in the version he supports and I can update this project accordingly.
