### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by colinskow** [kribblo/node-ffmpeg-installer#7]
I am running macOS 10.12.4 and it appears that this installer isn't giving proper executable permissions to the FFMPEG executable.

After I did it manually `chmod u+x /path/to/executable` it works fine. This should probably be done automatically via postinstall script.

Also applies to ffprobe-installer.

**Comment by kribblo** [comment]
Didn't know this was a problem, sounds like a reasonable solution; guess it would work with just adding this as a `"postinstall"` command to the [darwin-x64 package.json](https://github.com/kribblo/node-ffmpeg-installer/blob/master/platforms/darwin-x64/package.json)?

**Comment by kribblo** [comment]
Also, not associated with ffprobe-installer so you'll have to file a separate bug with them, even though it's a fork of this project.

**Comment by kribblo** [comment]
Adde postinstall script in 1.0.10:

     "postinstall": "chmod u+x ffmpeg"

@colinskow could you please test it? I don't have a mac readily available. Thanks!

**Comment by colinskow** [comment]
I'll test it tomorrow and let you know... Thanks for the quick fix!

**Comment by colinskow** [comment]
We sound also test on Linux.

**Comment by kribblo** [comment]
I did not make the change on Linux (it's separate sub-projects); I'm using Linux and it's been working for me (which is why I didn't know this was an issue). Possibly this is due to me making the packages on Linux and the executable flag not being set or not carried over to Mac?

If this works we can add the same change there too, though, because it wouldn't hurt after all.

**Comment by colinskow** [comment]
OK, I've tested it on Mac and it works! Thank you very much for the quick fix.

**Comment by colinskow** [comment]
Next opportunity I will test on Windows.

**Comment by kribblo** [comment]
Added the same postinstall for Linux just in case and closing this.

Windows does not use executable permissions in the same way, rather (IIRC) it's a combination of extension (like .exe) and the file containing a few marker bytes in the start of the file. However, any testing is appreciated and I don't use Windows myself either, so please!
