### ISSUE TITLE
Issue using package when deploying to Azure

### ISSUE THREAD

**Issue by cgordon5025** [kribblo/node-ffmpeg-installer#71]
When deployed to Azure I received this error

``
Error: Could not find ffmpeg executable, tried "C:\home\site\wwwroot\server\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe", "C:\home\site\wwwroot\server\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe" and "C:\home\site\wwwroot\server\node_modules\@ffmpeg-installer\win32-ia32\ffmpeg.exe"
``

I wrote the code on a windows device and as such the folder downloaded with the module was the win32-x64 folder. However looking at the files in Azure it downloaded the Linux folder instead, due to Azure running on Linux. 

Is there a way around this, or a step I am missing?

**Comment by KelvinTseTR** [comment]
I got similar issue when deploy to Azure function. Would you mind to share how do you resolve that?
