### ISSUE TITLE
libopus support

### ISSUE THREAD

**Issue by davehorton** [kribblo/node-ffmpeg-installer#8]
I get an error when I try to decode an opus file (unknown format 'opus').

Is opus intended to be supported?  If not any plans to do so, or suggestions on how to possibly make it work?

**Comment by kribblo** [comment]
I use prebuilt binaries that others provide: https://github.com/kribblo/node-ffmpeg-installer#the-binaries

They can probably vary some between platforms and each such provider decides what encodings to include. I'd be very happy to update the binaries here if the original provider (or some other reliable one) is willing to provide, but I won't be starting to compile my own binaries. :)

Maybe try contacting the guy for your platform(s) and ask there?

**Comment by kribblo** [comment]
Hmmm actually, looking at the builds, looks like they *should* be compiled with libopus, so maybe I just need to update to newer versions. Which platform are you on @davehorton , I can try that one first?

**Comment by kribblo** [comment]
All binaries updated to the latest versions, docs say that libopus should be enabled in all; please try it out.

Closing this, if it still doesn't work then try the corresponding binary directly and see if that may be the problem.

Thanks for the report!
